name: Deploy Next.js Frontend

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      NEXT_PUBLIC_CHAIN_ID: ${{ vars.NEXT_PUBLIC_CHAIN_ID }}
      NEXT_PUBLIC_RPC_BASE_URL: ${{ vars.NEXT_PUBLIC_RPC_BASE_URL }}
      NEXT_PUBLIC_RPC_SEPOLIA_BASE_URL: ${{ vars.NEXT_PUBLIC_RPC_SEPOLIA_BASE_URL }}
      NEXT_PUBLIC_POOL_MANAGER_BASE_ADDR: ${{ vars.NEXT_PUBLIC_POOL_MANAGER_BASE_ADDR }}
      NEXT_PUBLIC_POOL_MANAGER_SEPOLIA_BASE_ADDR: ${{ vars.NEXT_PUBLIC_POOL_MANAGER_SEPOLIA_BASE_ADDR }}
      NEXT_PUBLIC_HOOK_BASE_ADDR: ${{ vars.NEXT_PUBLIC_HOOK_BASE_ADDR }}
      NEXT_PUBLIC_HOOK_SEPOLIA_BASE_ADDR: ${{ vars.NEXT_PUBLIC_HOOK_SEPOLIA_BASE_ADDR }}
      NEXT_PUBLIC_TOKEN0_ADDR: ${{ vars.NEXT_PUBLIC_TOKEN0_ADDR }}
      NEXT_PUBLIC_TOKEN1_ADDR: ${{ vars.NEXT_PUBLIC_TOKEN1_ADDR }}
      NEXT_PUBLIC_SWAP_ROUTER_BASE_ADDR: ${{ vars.NEXT_PUBLIC_SWAP_ROUTER_BASE_ADDR }}
      NEXT_PUBLIC_SWAP_ROUTER_SEPOLIA_BASE_ADDR: ${{ vars.NEXT_PUBLIC_SWAP_ROUTER_SEPOLIA_BASE_ADDR }}
      NEXT_PUBLIC_STATE_VIEW_BASE_ADDR: ${{ vars.NEXT_PUBLIC_STATE_VIEW_BASE_ADDR }}
      NEXT_PUBLIC_STATE_VIEW_SEPOLIA_BASE_ADDR: ${{ vars.NEXT_PUBLIC_STATE_VIEW_SEPOLIA_BASE_ADDR }}
      NEXT_PUBLIC_DEMO_BATCHER: ${{ vars.NEXT_PUBLIC_DEMO_BATCHER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build with Next.js
        run: npm run build
        working-directory: ./frontend

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend/out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
